version: '3.1'

services:
  tomcat:
    build: ./tomcat
    image: tomcat-image2
    container_name: tomcat
    ports:
      - 8081:8080
    volumes:
      - ./tomcat/share/logs:/share/logs
